config/routes.rb
Rails.application.routes.draw do
  resources :event_attendances, only: %i[new create]
  resources :events
  resources :users
  root 'events#index'
  resources :sessions, only: %i[index new create destroy]
  get 'show_events', to: 'users#show', as: 'show_events'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'home', to: 'events#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id
  has_many :event_attendances, foreign_key: :event_attended_id, class_name: 'EventAttendance'
  has_many :attendees, through: :event_attendances
  scope :past, -> { where('event_date<?', Time.now) }
  scope :future, -> { where('event_date>?', Time.now) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, foreign_key: 'attendee_id', class_name: 'User'
  belongs_to :event_attended, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :event_attendances, foreign_key: :attendee_id, class_name: 'EventAttendance'
  has_many :event_attended, through: :event_attendances
  validates :name, presence: true, length: { minimum: 3 }
  validates :username, presence: true, length: { minimum: 4 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  def new
    @event_attendance = EventAttendance.new
  end

  def create
    @event_attendance = EventAttendance.create(event_attendance_params)
  end

  private

  def event_attendance_params
    params.require(:event_attendance).permit(:attendee_id, :event_attended_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @previous_events = Event.past
    @upcoming_events = Event.future
    @event = Event.new
    @event_attendance = EventAttendance.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
      else
        format.html { render 'form' }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :event_date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash.now[:alert] = 'Incorrect username'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

  def index
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_to login_path unless logged_in?
  end

  def show
    redirect_to login_path unless logged_in?
    @attended_events = current_user.event_attended
    @upcoming_events = current_user.created_events.future
    @previous_events = current_user.created_events.past
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_buttons
    if logged_in?
      content_tag :div do
        content_tag(:button, 'Home', onclick: "location.href = '../';", class: 'btn btn-success mr-2') +
          content_tag(:button, 'New Event', onclick: "location.href = '../events/new';",
                                            class: 'btn btn-success mr-2') +
          content_tag(:button, 'Show Events', onclick: "location.href = '../show_events';",
                                              class: 'btn btn-success mr-2') +
          content_tag(:button, current_user.name, onclick: "location.href = '../users';",
                                                  class: 'btn btn-success mr-2') +
          content_tag(:button, 'Logout', onclick: "location.href = '../logout';", class: 'btn btn-success')
      end
    else
      content_tag :div do
        content_tag(:button, 'Sign Up', onclick: "location.href = '../signup';", class: 'btn btn-success mr-2') +
          content_tag(:button, 'Login', onclick: "location.href = '../login';", class: 'btn btn-success')
      end
    end
  end
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_form
    render 'form' if logged_in?
  end

  def button(event)
    if logged_in?
      if !EventAttendance.exists?(attendee_id: current_user.id, event_attended_id: event.id)
        render 'attendance_button', event: event
      else
        content_tag(:button, 'Attend', class: 'btn btn-success float-right mt-2', disabled: true)
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def alert_error
    tag = content_tag :ul do
      content_tag(:li, alert, class: 'errors')
    end
    tag if alert
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendances/_form.html.erb
<%= form_with(model: event_attendance, local: true) do |form| %>
  <% if event_attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_attendance.errors.count, "error") %> prohibited this event_attendance from being saved:</h2>

      <ul>
        <% event_attendance.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attendee_id %>
    <%= form.number_field :attendee_id %>
  </div>

  <div class="field">
    <%= form.label :evnt_attended_id %>
    <%= form.number_field :evnt_attended_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_attendances/edit.html.erb
<h1>Editing Event Attendance</h1>

<%= render 'form', event_attendance: @event_attendance %>

<%= link_to 'Show', @event_attendance %> |
<%= link_to 'Back', event_attendances_path %>

app/views/event_attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Attendee</th>
      <th>Evnt attended</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_attendances.each do |event_attendance| %>
      <tr>
        <td><%= event_attendance.attendee_id %></td>
        <td><%= event_attendance.evnt_attended_id %></td>
        <td><%= link_to 'Show', event_attendance %></td>
        <td><%= link_to 'Edit', edit_event_attendance_path(event_attendance) %></td>
        <td><%= link_to 'Destroy', event_attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Attendance', new_event_attendance_path %>

app/views/event_attendances/new.html.erb
<h1>New Event Attendance</h1>

<%= render 'form', event_attendance: @event_attendance %>

<%= link_to 'Back', event_attendances_path %>

app/views/event_attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attendee:</strong>
  <%= @event_attendance.attendee_id %>
</p>

<p>
  <strong>Evnt attended:</strong>
  <%= @event_attendance.evnt_attended_id %>
</p>

<%= link_to 'Edit', edit_event_attendance_path(@event_attendance) %> |
<%= link_to 'Back', event_attendances_path %>

app/views/events/_attendance_button.html.erb
<%= simple_form_for @event_attendance do |f| %>
  <%= f.hidden_field :attendee_id, :value => current_user.id %>
  <%= f.hidden_field :event_attended_id, :value => event.id %>
  <%= f.button :submit, "Attend", class: "btn-success float-right mt-2" %>
<% end %>

app/views/events/_form.html.erb
<h3>Create a new event</h3>
<%= simple_form_for @event, :html => {:class => "bg-info mb-3 p-3"} do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: "Event title", placeholder: "Add title here..." %>
  <%= f.input :event_date, label: "Event date" %>
  <%= f.input :description, label: "Event Description", placeholder: "Add event description here..." %>
  <%= f.button :submit, class: "btn-success" %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id='notice'><%= notice %></p>
<div class="container mt-5">
  <%= event_form %>

  <div class="container">
    <div class="row">
      <div class="col">
      <h1 class="text-success mr-2 hi_title">Upcoming Events:</h1>
      <div class="results-column d-flex flex-column p-2">
         <% @upcoming_events.each do |event| %>
           <div class="p-3 mb-1" style="background-color:lavender;">
             <div class="d-flex justify-content-between">
               <h4 class="text-dark"><%= link_to "#{event.title}", event, class: "text-dark" %></h4>
          <div class="text-info"><%= event.event_date %></div>
        </div>
        <div><%= event.description %></div>
        <%= button(event) %>
      </div>
    <% end %>
  </div></div>
      <div class="col">
      <h1 class="text-danger hi_title">Previous Events:</h1>
  <div class="results-column d-flex flex-column p-2">
    <% @previous_events.each do |event| %>
      <div class="p-3 mb-1" style="background-color:lavender;">
        <div class="d-flex justify-content-between">
          <h4 class="text-dark"><%= link_to "#{event.title}", event, class: "text-dark" %></h4>
          <div class="text-info"><%= event.event_date %></div>
        </div>
        <div><%= event.description %></div>
        <%= button(event) %>
      </div>
    <% end %>
  </div>
  </div>
    </div>
  </div>
  
</div>

app/views/events/new.html.erb
<% if logged_in? %>
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
<% else %>
<%= flash[:notice] = "You have to Login Or Sign Up" %>
<% end %>

app/views/events/show.html.erb
<div class="container">
  <div class="results-column d-flex flex-column p-5 w-50 m-auto">
      <div class="bg-light p-4 mb-2" >
        <div class="d-flex justify-content-between">
          <h4 class="text-secondary"><%= @event.title %></h4>
          <div class="text-success"><%= @event.event_date %></div>
        </div>
        <div><%= @event.description %></div>
      </div>
  </div>
  <div class="results-column d-flex flex-column p-2 w-50 m-auto text-center">
    <p id="notice"><%= notice %></p>
  <h1>List of attendees</h1>
  <table >
    <thead>
      <tr>
        <th> <u> Name </u> </th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @event.attendees.each do |attendee| %>
        <tr>
          <td><%= attendee.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back', root_path, class: 'p-3' %>
  </div>
</div>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
  </head>
  <body>
    <nav class="navbar bg-primary d-flex justify-content-between align-items-center">
      <button class="mlogo" onclick="location.href = '../home';">PrivateEvents</button>
      <%= nav_buttons %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container d-flex justify-content-center">
<%= form_for @user, :validate => true, :html => {:class => "form-input"} do |f| %>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li class="errors"><%= error %></li>
    <% end %>
  </ul>
  <div class="input-field">
    <div class="labels">
      <label class="form-label">Name :</label>
    </div>
    <div><%= f.text_field :name, :placeholder =>  'enter name', :class => "inputbox" %></div>
  </div>
  <div class="input-field">
    <div class="labels">
      <label class="form-label mt-2 mb-2">Username :</label>
    </div>
    <div><%= f.text_field :username, :placeholder =>  'enter username',:class => "inputbox" %></div>
  </div>
  <div>
    <%= f.submit("Submit", :class => "btn btn-secondary btn-block mb-3 mt-3") %>
  </div>
  <button type="button" onclick="location.href = 'login';" class="btn btn-success btn-block mb-3" >Login</button>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'form', user: @user %>
  <button onclick="location.href = '../';" class="btn btn-success" >Back</button>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h4>User profile</h4>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Username</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= current_user.name %></td>
        <td><%= current_user.username %></td>
        <td><%= link_to 'Edit', edit_user_path(current_user) %></td>
        <td><%= link_to 'Destroy', current_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
  </table>
  <br>
  <button onclick="location.href = 'show_events';" class="btn btn-sm btn-success mb-2" >Show events</button> <br>
  <button onclick="location.href = '../';" class="btn btn-sm btn-success" >Home page</button>
</div>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<main class="container">
  <section class="signup-form bg-light">
    <h4 class="text-center">
      Create a new account
    </h4>
    <%= render "form" , user: @user %>
  </section>
</main>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  
  <div>
    <div class="row">

    <div class="col">
    <h2 class="text-primary">Events Attending</h2>
    <div class="results-column d-flex flex-column p-3">
    <% @attended_events.each do |event| %>
      <div class="bg-light p-2 mb-2" >
        <div class="d-flex justify-content-between">
          <h4 class="text-secondary"><%= event.title %></h4>
          <div class="text-success"><%= event.event_date %></div>
        </div>
        <div><%= event.description %></div>
      </div>
    <% end %>
  </div>
    </div>
    
    <div class="col">
    <h2 class="text-success"> Created Events </h2>
    <br>
    <h4>Upcoming events</h4>
    <div class="results-column d-flex flex-column p-3">
      <% @upcoming_events.each do |event| %>
        <div class="bg-light p-2 mb-2" >
          <div class="d-flex justify-content-between">
            <h4><%= link_to "#{event.title}", event, class: "text-secondary" %></h4>
            <div class="text-success"><%= event.event_date %></div>
          </div>
          <div><%= event.description %></div>
        </div>
      <% end %>
    </div>
    <h4>Previous events</h4>
    <div class="results-column d-flex flex-column p-3">
      <% @previous_events.each do |event| %>
        <div class="bg-light p-2 mb-2" >
          <div class="d-flex justify-content-between">
            <h4><%= link_to "#{event.title}", event, class: "text-secondary" %></h4>
            <div class="text-success"><%= event.event_date %></div>
          </div>
          <div><%= event.description %></div>
        </div>
      <% end %>
    </div>

    </div>

    </div>
    
  </div>
  <button onclick="location.href = '../users';" class="btn btn-success" >Back</button>